from daily_win_api.domains.learning.enums import SkillDomain, SkillStateMode

SKILL_DEFINITIONS: tuple[dict[str, str], ...] = (
    {
        "code": "math.number_sense",
        "domain": SkillDomain.MATH,
        "display_name": "Number sense",
        "description": "Understanding quantities, counting, and number relationships.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "math.addition",
        "domain": SkillDomain.MATH,
        "display_name": "Addition",
        "description": "Combining quantities accurately.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "math.subtraction",
        "domain": SkillDomain.MATH,
        "display_name": "Subtraction",
        "description": "Finding differences between quantities.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "math.multiplication",
        "domain": SkillDomain.MATH,
        "display_name": "Multiplication",
        "description": "Understanding equal groups and products.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "math.fractions",
        "domain": SkillDomain.MATH,
        "display_name": "Fractions",
        "description": "Understanding parts of a whole.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "reading.phonics",
        "domain": SkillDomain.READING,
        "display_name": "Phonics",
        "description": "Connecting letters and sounds.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "reading.fluency",
        "domain": SkillDomain.READING,
        "display_name": "Fluency",
        "description": "Reading accurately, smoothly, and with expression.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "reading.vocabulary",
        "domain": SkillDomain.READING,
        "display_name": "Vocabulary",
        "description": "Understanding and using new words.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "reading.comprehension",
        "domain": SkillDomain.READING,
        "display_name": "Comprehension",
        "description": "Understanding what a text means.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "writing.spelling",
        "domain": SkillDomain.WRITING,
        "display_name": "Spelling",
        "description": "Encoding words accurately.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "writing.sentences",
        "domain": SkillDomain.WRITING,
        "display_name": "Sentences",
        "description": "Writing complete, clear sentences.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "writing.organization",
        "domain": SkillDomain.WRITING,
        "display_name": "Organization",
        "description": "Ordering ideas so writing is easy to follow.",
        "state_mode": SkillStateMode.MASTERY,
    },
    {
        "code": "growth.persistence",
        "domain": SkillDomain.GROWTH,
        "display_name": "Persistence",
        "description": "Continuing after an initial setback.",
        "state_mode": SkillStateMode.TREND,
    },
    {
        "code": "growth.independence",
        "domain": SkillDomain.GROWTH,
        "display_name": "Independence",
        "description": "Trying a next step with less adult prompting.",
        "state_mode": SkillStateMode.TREND,
    },
    {
        "code": "growth.communication",
        "domain": SkillDomain.GROWTH,
        "display_name": "Communication",
        "description": "Expressing ideas and feelings clearly.",
        "state_mode": SkillStateMode.TREND,
    },
    {
        "code": "growth.problem_solving",
        "domain": SkillDomain.GROWTH,
        "display_name": "Problem solving",
        "description": "Trying strategies when something is hard.",
        "state_mode": SkillStateMode.TREND,
    },
    {
        "code": "life.money",
        "domain": SkillDomain.LIFE,
        "display_name": "Money",
        "description": "Practical money sense for everyday situations.",
        "state_mode": SkillStateMode.TREND,
    },
    {
        "code": "life.organization",
        "domain": SkillDomain.LIFE,
        "display_name": "Organization",
        "description": "Keeping materials and steps in a workable order.",
        "state_mode": SkillStateMode.TREND,
    },
    {
        "code": "life.decision_making",
        "domain": SkillDomain.LIFE,
        "display_name": "Decision making",
        "description": "Choosing a next step with growing judgment.",
        "state_mode": SkillStateMode.TREND,
    },
)
