"""create daily wins and ai runs

Revision ID: dac0a25a697d
Revises: 737ad5a0a455
Create Date: 2026-09-17 16:38:47.784902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dac0a25a697d'
down_revision: Union[str, Sequence[str], None] = '737ad5a0a455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_runs',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_schema_version', sa.String(length=16), nullable=False),
    sa.Column('output_schema_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('context_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id', 'household_id'], ['children.id', 'children.household_id'], name='fk_ai_runs_child_household', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_runs_household_child', 'ai_runs', ['household_id', 'child_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_status'), 'ai_runs', ['status'], unique=False)
    op.create_table('daily_wins',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('primary_skill_id', sa.Uuid(), nullable=False),
    sa.Column('ai_run_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_schema_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['child_id', 'household_id'], ['children.id', 'children.household_id'], name='fk_daily_wins_child_household', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['primary_skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_wins_ai_run_id'), 'daily_wins', ['ai_run_id'], unique=False)
    op.create_index('ix_daily_wins_household_child', 'daily_wins', ['household_id', 'child_id'], unique=False)
    op.create_index(op.f('ix_daily_wins_primary_skill_id'), 'daily_wins', ['primary_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_wins_primary_skill_id'), table_name='daily_wins')
    op.drop_index('ix_daily_wins_household_child', table_name='daily_wins')
    op.drop_index(op.f('ix_daily_wins_ai_run_id'), table_name='daily_wins')
    op.drop_table('daily_wins')
    op.drop_index(op.f('ix_ai_runs_status'), table_name='ai_runs')
    op.drop_index('ix_ai_runs_household_child', table_name='ai_runs')
    op.drop_table('ai_runs')
    # ### end Alembic commands ###
